- name: Deploy MPE JITP
  hosts: localhost
  gather_facts: no
  tasks:
   - name: Create a worker VM from template
     with_items:
       - [ 1, 2, 3, 4, 5 ]
     vmware_guest:
       hostname: 10.79.47.152
       username: administrator@vsphere.local
       password: Cisco!23
       validate_certs: no
       datacenter: guayou-b12-small-ivp
       cluster: ivp
       template: ivp-coe-template
       resource_pool: ivp
       folder: ivp
       name: ivpworker_w{{ item }}
       state: poweredon
     delegate_to: localhost
     register: deploy_worker

   - name: Create a edge worker VM template
     with_items:
       - [ 1, 2, 3, 4 ]
     vmware_guest:
       hostname: 10.79.47.152
       username: administrator@vsphere.local
       password: Cisco!23
       validate_certs: no
       datacenter: guayou-b12-small-ivp
       cluster: ivp
       resource_pool: ivp
       template: ivp-coe-template
       folder: ivp
       name: ivpworker_e{{ item }}
       state: poweredon
         
     delegate_to: localhost
     register: deploy_worker_e

   - name: Create a master VM template
     vmware_guest:
       hostname: 10.79.47.152
       username: administrator@vsphere.local
       password: Cisco!23
       template: ivp-coe-template
       validate_certs: no
       datacenter: guayou-b12-small-ivp
       cluster: ivp
       resource_pool: ivp
       folder: ivp
       name: ivpworker_m
       state: poweredon
     delegate_to: localhost
     register: deploy_master

   - name: get vm Info
     local_action: copy content={{ item }} dest="/path/to/destination/file{{ item.msg.results.item }}"
     with_items:
       - "{{ deploy_worker }}"
       - "{{ deploy_worker_e }}"
       - "{{ deploy_master }}"

